### ISSUE TITLE
Better lens name suffix

### ISSUE THREAD

**Issue by cfhammill** [cfhammill/focal#3]
I've been suffixing lenses and lens constructors with `l`, might be less likely to clash with real words if we suffix `..` instead. Adds an extra char but I think it would be worth it. So `selectl` would be `select..` instead

**Comment by bcdarwin** [comment]
I think people will complain these are noisy (and the two dots in a row are kind of weird tbh).  What about `_l`?

**Comment by cfhammill** [comment]
Sold. Renaming lenses `*_l` and `over` to `lset` and `view` to `lget`
